# Generated by Django 6.0.6 on 2026-07-14 03:59

import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=singer.models.image_upload_path),
        ),
    ]
